CLR P0.7 ; ENABLE DAC

MOV TMOD, #15H ; TIMER 1 IN MODE 1 AND TIMER 0 AS COUNTER IN MODE 1
MOV TH0, #00H
MOV TL0, #00H
SETB TR0 ; START COUNTER
MOV TH1, #0D8H
MOV TL1, #0F0H ; TIMER FOR 10 mS
SETB TR1 ; START TIMER

LOOP:
MOV P1, #00H ; LOW STATE OF WAVE
MOV P3, #00H
ACALL DELAY ; DELAY OF 250 uSec
MOV P1, #0FFH ; HIGH STATE OF WAVE
MOV P3, #0FFH
ACALL DELAY ; DELAY OF 250 uSec
JNB TF1, LOOP
JMP FINISH

DELAY:
MOV B, #7BH; OVERALL DELAY OF 125 uSec INCLUDING OTHER INSTRUCTIONS
DJNZ B, $
RET

FINISH:
END
